<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_head\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\',bigclass =\'0\'',
  1 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_product\',value=\'\',defaultvalue=\'\',valueinfo =\'首页产品区块\',tips=\'\',bigclass =\'0\'',
  2 => 'pos =\'3\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'news_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  3 => 'pos =\'2\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_download\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  4 => 'pos =\'0\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'navbarok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉菜单\',tips=\'\',bigclass =\'524\'',
  5 => 'pos =\'1\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'545\'',
  6 => 'pos =\'3\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column3_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'592\'',
  7 => 'pos =\'2\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'download\',value=\'立即下载\',defaultvalue=\'立即下载\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'604\'',
  8 => 'pos =\'2\',no_order=\'3\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  9 => 'pos =\'0\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_ml\',value=\'10\',defaultvalue=\'10\',valueinfo =\'导航间距\',tips=\'默认是0，仅支持5的倍数（0/5/10/15/20...最大50）<br/>不同网站的导航数量不同，根据需求适当调整间距，让网站更协调。\',bigclass =\'524\'',
  10 => 'pos =\'1\',no_order=\'3\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_product_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'545\'',
  11 => 'pos =\'3\',no_order=\'3\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'592\'',
  12 => 'pos =\'2\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$浏览模式$T$1$M$详情模式$T$0\',name =\'img_listlook_style\',value=\'1\',defaultvalue=\'1\',valueinfo =\'查看模式\',tips=\'浏览模式为在列表页浏览图片，详情模式为点击进入详情页\',bigclass =\'458\'',
  13 => 'pos =\'0\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'下拉菜单全部\',tips=\'仅在手机端显示\',bigclass =\'524\'',
  14 => 'pos =\'1\',no_order=\'4\',type=\'6\',style=\'3\',selectd=\'\',name =\'index_product_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'\',bigclass =\'545\'',
  15 => 'pos =\'3\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'592\'',
  16 => 'pos =\'0\',no_order=\'5\',type=\'4\',style=\'3\',selectd=\'$M$头部$T$1$M$底部$T$0\',name =\'langlist_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'多语言位置\',tips=\'\',bigclass =\'524\'',
  17 => 'pos =\'2\',no_order=\'5\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_job\',value=\'\',defaultvalue=\'\',valueinfo =\'招聘模块\',tips=\'\',bigclass =\'0\'',
  18 => 'pos =\'1\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_allnum\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'每个列表调用信息最多条数\',bigclass =\'545\'',
  19 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\',bigclass =\'592\'',
  20 => 'pos =\'0\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'langlist1_icon_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言国旗开关\',tips=\'\',bigclass =\'524\'',
  21 => 'pos =\'2\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'cvtitle\',value=\'在线应聘\',defaultvalue=\'在线应聘\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'543\'',
  22 => 'pos =\'1\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'index_product_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'列表信息调用类型，【推荐】可以在添加或管理文章列表时设置。\',bigclass =\'545\'',
  23 => 'pos =\'3\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表文章数量\',tips=\'\',bigclass =\'592\'',
  24 => 'pos =\'2\',no_order=\'7\',type=\'1\',style=\'3\',selectd=\'\',name =\'subcolumn_nav\',value=\'\',defaultvalue=\'\',valueinfo =\'子栏目设置\',tips=\'\',bigclass =\'0\'',
  25 => 'pos =\'0\',no_order=\'7\',type=\'9\',style=\'3\',selectd=\'\',name =\'head_bgcolor\',value=\'\',defaultvalue=\'\',valueinfo =\'导航背景色\',tips=\'默认是透明\',bigclass =\'524\'',
  26 => 'pos =\'1\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_w\',value=\'640\',defaultvalue=\'640\',valueinfo =\'缩略图宽\',tips=\'默认为640px\',bigclass =\'545\'',
  27 => 'pos =\'3\',no_order=\'7\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'news_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表文章类型\',tips=\'\',bigclass =\'592\'',
  28 => 'pos =\'2\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_2\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块开关\',tips=\'\',bigclass =\'460\'',
  29 => 'pos =\'1\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_h\',value=\'439\',defaultvalue=\'439\',valueinfo =\'缩略图高\',tips=\'默认为439px\',bigclass =\'545\'',
  30 => 'pos =\'3\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'product_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏热门产品开关\',tips=\'\',bigclass =\'592\'',
  31 => 'pos =\'0\',no_order=\'8\',type=\'9\',style=\'3\',selectd=\'\',name =\'headcolumn_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'一级导航栏目颜色\',tips=\'默认是#000000\',bigclass =\'524\'',
  32 => 'pos =\'2\',no_order=\'9\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_news\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  33 => 'pos =\'1\',no_order=\'9\',type=\'4\',style=\'3\',selectd=\'背景色$T$1$M$背景图片$T$0\',name =\'bg_type\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块背景类型\',tips=\'默认是背景色\',bigclass =\'545\'',
  34 => 'pos =\'3\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_bar_list_num\',value=\'3\',defaultvalue=\'3\',valueinfo =\'侧栏热门产品数量\',tips=\'默认是3条\',bigclass =\'592\'',
  35 => 'pos =\'0\',no_order=\'9\',type=\'9\',style=\'3\',selectd=\'\',name =\'headsubcolumn_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'二级导航栏颜色\',tips=\'默认是#000000\',bigclass =\'524\'',
  36 => 'pos =\'2\',no_order=\'10\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_imgok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'图片开关\',tips=\'\',bigclass =\'449\'',
  37 => 'pos =\'1\',no_order=\'10\',type=\'9\',style=\'3\',selectd=\'\',name =\'index_product_bgcolor\',value=\'#f5f5f5f5\',defaultvalue=\'#f5f5f5f5\',valueinfo =\'区块背景色\',tips=\'默认是#f5f5f5\',bigclass =\'545\'',
  38 => 'pos =\'3\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_bar_list_title\',value=\'热门产品\',defaultvalue=\'热门产品\',valueinfo =\'侧栏热门产品标题\',tips=\'\',bigclass =\'592\'',
  39 => 'pos =\'0\',no_order=\'10\',type=\'9\',style=\'3\',selectd=\'\',name =\'headcolumn_activecolor\',value=\'#ffffff\',defaultvalue=\'#ffffff\',valueinfo =\'导航栏目激活色和鼠标经过色\',tips=\'默认是#ffffff\',bigclass =\'524\'',
  40 => 'pos =\'1\',no_order=\'11\',type=\'7\',style=\'3\',selectd=\'\',name =\'index_product_bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px高自定义的图片\',bigclass =\'545\'',
  41 => 'pos =\'3\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'product_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏热门产品类型\',tips=\'\',bigclass =\'592\'',
  42 => 'pos =\'2\',no_order=\'11\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_product\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块\',tips=\'\',bigclass =\'0\'',
  43 => 'pos =\'0\',no_order=\'11\',type=\'9\',style=\'3\',selectd=\'\',name =\'headcolumnitem_color\',value=\'#ffffff\',defaultvalue=\'#ffffff\',valueinfo =\'导航栏目激活背景色\',tips=\'默认是#ffffff\',bigclass =\'524\'',
  44 => 'pos =\'0\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_position\',value=\'\',defaultvalue=\'\',valueinfo =\'当前位置\',tips=\'\',bigclass =\'0\'',
  45 => 'pos =\'3\',no_order=\'12\',type=\'6\',style=\'3\',selectd=\'\',name =\'product_bar_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\',bigclass =\'592\'',
  46 => 'pos =\'2\',no_order=\'12\',type=\'9\',style=\'3\',selectd=\'\',name =\'product_btncolor\',value=\'\',defaultvalue=\'\',valueinfo =\'查看详情文字颜色\',tips=\'默认是模板配色\',bigclass =\'640\'',
  47 => 'pos =\'1\',no_order=\'12\',type=\'9\',style=\'3\',selectd=\'\',name =\'product_titlecolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'标题颜色\',tips=\'默认是#000\',bigclass =\'545\'',
  48 => 'pos =\'3\',no_order=\'13\',type=\'1\',style=\'3\',selectd=\'\',name =\'downlaod_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  49 => 'pos =\'0\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'position_text\',value=\'你的位置\',defaultvalue=\'你的位置\',valueinfo =\'当前位置标题\',tips=\'\',bigclass =\'462\'',
  50 => 'pos =\'2\',no_order=\'13\',type=\'9\',style=\'3\',selectd=\'\',name =\'product_desccolor\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字颜色\',tips=\'默认是模板副色\',bigclass =\'640\'',
  51 => 'pos =\'1\',no_order=\'13\',type=\'9\',style=\'3\',selectd=\'\',name =\'productdesc_color\',value=\'#666\',defaultvalue=\'#666\',valueinfo =\'描述颜色\',tips=\'默认是#666\',bigclass =\'545\'',
  52 => 'pos =\'3\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_title\',value=\'为你推荐\',defaultvalue=\'为你推荐\',valueinfo =\'侧栏下载列表标题\',tips=\'\',bigclass =\'451\'',
  53 => 'pos =\'0\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区域开关\',tips=\'\',bigclass =\'462\'',
  54 => 'pos =\'2\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_moredesc\',value=\'查看详情\',defaultvalue=\'查看详情\',valueinfo =\'查看更多\',tips=\'\',bigclass =\'640\'',
  55 => 'pos =\'1\',no_order=\'14\',type=\'9\',style=\'3\',selectd=\'\',name =\'productimg_color\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'图片标题颜色\',tips=\'默认是#000\',bigclass =\'545\'',
  56 => 'pos =\'0\',no_order=\'15\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_foot\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\',bigclass =\'0\'',
  57 => 'pos =\'3\',no_order=\'15\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_downloadlist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏下载列表数量\',tips=\'\',bigclass =\'451\'',
  58 => 'pos =\'2\',no_order=\'15\',type=\'9\',style=\'3\',selectd=\'\',name =\'product_item_bgcolor\',value=\'#f6f6f6\',defaultvalue=\'#f6f6f6\',valueinfo =\'列表区块背景色\',tips=\'默认是#f6f6f6\',bigclass =\'640\'',
  59 => 'pos =\'1\',no_order=\'15\',type=\'9\',style=\'3\',selectd=\'\',name =\'morebtn_bgcolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'more按钮背景色\',tips=\'默认是#000\',bigclass =\'545\'',
  60 => 'pos =\'0\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'link_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'友情链接开关\',tips=\'\',bigclass =\'444\'',
  61 => 'pos =\'3\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'download_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表下载类型\',tips=\'\',bigclass =\'451\'',
  62 => 'pos =\'2\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'more\',value=\'more\',defaultvalue=\'more\',valueinfo =\'查看更多文本\',tips=\'手机端不显示\',bigclass =\'640\'',
  63 => 'pos =\'1\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\',bigclass =\'545\'',
  64 => 'pos =\'0\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'footlink_title\',value=\'友情链接\',defaultvalue=\'友情链接\',valueinfo =\'友情链接标题\',tips=\'\',bigclass =\'444\'',
  65 => 'pos =\'3\',no_order=\'17\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'download_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'451\'',
  66 => 'pos =\'2\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_maxh\',value=\'350\',defaultvalue=\'350\',valueinfo =\'图片模块最大高度\',tips=\'默认为350 （定义图片外层区块的最大高度，内层图片高出的话会有个隐藏的滚动条，滚动条在内侧可滚动）\',bigclass =\'640\'',
  67 => 'pos =\'1\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于或等于768像素且小于992像素\',bigclass =\'545\'',
  68 => 'pos =\'0\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$底部$T$0$M$顶部$T$1\',name =\'cn1_position\',value=\'0\',defaultvalue=\'0\',valueinfo =\'简繁体切换按钮位置\',tips=\'\',bigclass =\'444\'',
  69 => 'pos =\'3\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'downloadsidebar_column_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'451\'',
  70 => 'pos =\'2\',no_order=\'18\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_borcolor\',value=\'#e8e8e8\',defaultvalue=\'#e8e8e8\',valueinfo =\'内容边框颜色\',tips=\'默认为#E8E8E8\',bigclass =\'640\'',
  71 => 'pos =\'1\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_case_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器窗口宽度大于或等于992像素且小于1600像素\',bigclass =\'545\'',
  72 => 'pos =\'0\',no_order=\'19\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'cn1_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'简繁体切换开关\',tips=\'\',bigclass =\'444\'',
  73 => 'pos =\'3\',no_order=\'19\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'sidebar_downloadlist_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'451\'',
  74 => 'pos =\'2\',no_order=\'19\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_borhovcolor\',value=\'\',defaultvalue=\'\',valueinfo =\'内容边框鼠标经过颜色\',tips=\'默认继承模板配色调\',bigclass =\'640\'',
  75 => 'pos =\'1\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器窗口宽度大于或等于1600像素\',bigclass =\'545\'',
  76 => 'pos =\'3\',no_order=\'20\',type=\'1\',style=\'3\',selectd=\'\',name =\'img_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  77 => 'pos =\'2\',no_order=\'20\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_titlecolor\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题颜色\',tips=\'默认继承模板主色调\',bigclass =\'640\'',
  78 => 'pos =\'0\',no_order=\'20\',type=\'9\',style=\'3\',selectd=\'\',name =\'met_foot_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'底部背景色\',tips=\'默认是#f5f5f5\',bigclass =\'444\'',
  79 => 'pos =\'1\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'标题居左$T$1$M$标题居中$T$0\',name =\'img_titleposition\',value=\'1\',defaultvalue=\'1\',valueinfo =\'图片标题位置\',tips=\'默认是居左\',bigclass =\'545\'',
  80 => 'pos =\'3\',no_order=\'21\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏图片列表开关\',tips=\'\',bigclass =\'465\'',
  81 => 'pos =\'1\',no_order=\'21\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_about\',value=\'\',defaultvalue=\'\',valueinfo =\'首页简介区块\',tips=\'\',bigclass =\'0\'',
  82 => 'pos =\'2\',no_order=\'21\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_hrcolor\',value=\'#cccccc\',defaultvalue=\'#cccccc\',valueinfo =\'内容标题下方横线颜色\',tips=\'默认为#ccc\',bigclass =\'640\'',
  83 => 'pos =\'0\',no_order=\'21\',type=\'9\',style=\'3\',selectd=\'\',name =\'foot_columncolor\',value=\'#8080\',defaultvalue=\'#8080\',valueinfo =\'栏目文字颜色\',tips=\'默认是#808080\',bigclass =\'444\'',
  84 => 'pos =\'3\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏图片列表标题\',tips=\'\',bigclass =\'465\'',
  85 => 'pos =\'1\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'580\'',
  86 => 'pos =\'2\',no_order=\'22\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_hrhovcolor\',value=\'\',defaultvalue=\'\',valueinfo =\'内容标题下方横线鼠标经过颜色\',tips=\'默认继承模板配色调\',bigclass =\'640\'',
  87 => 'pos =\'0\',no_order=\'22\',type=\'9\',style=\'3\',selectd=\'\',name =\'footinfo_color\',value=\'#808080\',defaultvalue=\'#808080\',valueinfo =\'底部信息颜色\',tips=\'默认是#808080\',bigclass =\'444\'',
  88 => 'pos =\'3\',no_order=\'23\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'img_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表图片类型\',tips=\'\',bigclass =\'465\'',
  89 => 'pos =\'1\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'580\'',
  90 => 'pos =\'2\',no_order=\'23\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_desccolor\',value=\'\',defaultvalue=\'\',valueinfo =\'内容描述颜色\',tips=\'默认为模板副色调\',bigclass =\'640\'',
  91 => 'pos =\'0\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'tips\',value=\'\',defaultvalue=\'\',valueinfo =\'关注公众号\',tips=\'\',bigclass =\'444\'',
  92 => 'pos =\'3\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表图片数量\',tips=\'\',bigclass =\'465\'',
  93 => 'pos =\'1\',no_order=\'24\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'区块内容\',tips=\'\',bigclass =\'580\'',
  94 => 'pos =\'2\',no_order=\'24\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_morecolor\',value=\'\',defaultvalue=\'\',valueinfo =\'查看更多主颜色\',tips=\'默认继承模板配色调\',bigclass =\'640\'',
  95 => 'pos =\'0\',no_order=\'24\',type=\'7\',style=\'3\',selectd=\'\',name =\'tipsimg\',value=\'\',defaultvalue=\'\',valueinfo =\'关注公众号二维码\',tips=\'\',bigclass =\'444\'',
  96 => 'pos =\'3\',no_order=\'25\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'imgbar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'465\'',
  97 => 'pos =\'0\',no_order=\'25\',type=\'1\',style=\'3\',selectd=\'\',name =\'global\',value=\'\',defaultvalue=\'\',valueinfo =\'全局参数\',tips=\'\',bigclass =\'0\'',
  98 => 'pos =\'1\',no_order=\'25\',type=\'7\',style=\'3\',selectd=\'\',name =\'home_about_imgurl\',value=\'\',defaultvalue=\'\',valueinfo =\'电脑端顶部图片\',tips=\'建议图片尺寸是1920*550\',bigclass =\'580\'',
  99 => 'pos =\'2\',no_order=\'25\',type=\'9\',style=\'3\',selectd=\'\',name =\'box_morecolors\',value=\'#ffffff\',defaultvalue=\'#ffffff\',valueinfo =\'查看更多副颜色\',tips=\'默认为#ffffff\',bigclass =\'640\'',
  100 => 'pos =\'3\',no_order=\'26\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'465\'',
  101 => 'pos =\'0\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_font\',value=\'\',defaultvalue=\'\',valueinfo =\'页面字体\',tips=\'非特殊语种，建议留空使用模板默认字体\',bigclass =\'532\'',
  102 => 'pos =\'1\',no_order=\'26\',type=\'7\',style=\'3\',selectd=\'\',name =\'home_about_mbimgurl\',value=\'\',defaultvalue=\'\',valueinfo =\'手机端顶部图片\',tips=\'\',bigclass =\'580\'',
  103 => 'pos =\'3\',no_order=\'27\',type=\'1\',style=\'3\',selectd=\'\',name =\'product_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块侧边栏\',tips=\'\',bigclass =\'0\'',
  104 => 'pos =\'0\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'sub_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'页面文字\',tips=\'\',bigclass =\'532\'',
  105 => 'pos =\'1\',no_order=\'27\',type=\'9\',style=\'3\',selectd=\'\',name =\'abouttext_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'内容背景色\',tips=\'默认是#f5f5f5\',bigclass =\'580\'',
  106 => 'pos =\'3\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_title\',value=\'热门推荐\',defaultvalue=\'热门推荐\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'472\'',
  107 => 'pos =\'0\',no_order=\'28\',type=\'2\',style=\'3\',selectd=\'\',name =\'page_ajax_next\',value=\'加载更多\',defaultvalue=\'加载更多\',valueinfo =\'分页文字\',tips=\'无刷新分页默认文字\',bigclass =\'532\'',
  108 => 'pos =\'1\',no_order=\'28\',type=\'9\',style=\'3\',selectd=\'\',name =\'morebtn_color\',value=\'#ffffff\',defaultvalue=\'#ffffff\',valueinfo =\'按钮颜色\',tips=\'默认是模板主色\',bigclass =\'580\'',
  109 => 'pos =\'3\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'调用条数\',tips=\'\',bigclass =\'472\'',
  110 => 'pos =\'0\',no_order=\'29\',type=\'2\',style=\'3\',selectd=\'\',name =\'nodata\',value=\'没有数据了\',defaultvalue=\'没有数据了\',valueinfo =\'无数据提示\',tips=\'\',bigclass =\'532\'',
  111 => 'pos =\'1\',no_order=\'29\',type=\'4\',style=\'3\',selectd=\'关闭$T$1$M$开启$T$0\',name =\'home_about_img_ok\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部图片开关\',tips=\'默认是关闭\',bigclass =\'580\'',
  112 => 'pos =\'3\',no_order=\'30\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'product_sidebar_piclist_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'472\'',
  113 => 'pos =\'0\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'search_placeholder\',value=\'请输入内容关键词\',defaultvalue=\'请输入内容关键词\',valueinfo =\'搜索文字\',tips=\'\',bigclass =\'532\'',
  114 => 'pos =\'1\',no_order=\'30\',type=\'7\',style=\'3\',selectd=\'\',name =\'about_bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px高自定义的图片\',bigclass =\'580\'',
  115 => 'pos =\'3\',no_order=\'31\',type=\'4\',style=\'3\',selectd=\'当前一级栏目内容列表$T$1$M$TAG标签聚合$T$0\',name =\'product_sidebar_content\',value=\'1\',defaultvalue=\'1\',valueinfo =\'调用内容\',tips=\'默认调用当前栏目内容列表\',bigclass =\'472\'',
  116 => 'pos =\'0\',no_order=\'31\',type=\'9\',style=\'3\',selectd=\'\',name =\'first_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'模板主色调\',tips=\'\',bigclass =\'532\'',
  117 => 'pos =\'1\',no_order=\'31\',type=\'9\',style=\'3\',selectd=\'\',name =\'about_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'区块背景颜色\',tips=\'默认为#f5f5f5\',bigclass =\'580\'',
  118 => 'pos =\'0\',no_order=\'32\',type=\'4\',style=\'3\',selectd=\'当前窗口打开$T$target=_self$M$新窗口打开$T$target=_blank\',name =\'urlnew\',value=\'target=_self\',defaultvalue=\'target=_self\',valueinfo =\'内容列表链接打开方式\',tips=\'列表页链接打开方式可在栏目管理中对每个栏目进行单独设置\',bigclass =\'532\'',
  119 => 'pos =\'1\',no_order=\'32\',type=\'4\',style=\'3\',selectd=\'背景色$T$1$M$背景图片$T$0\',name =\'aboutbg_type\',value=\'1\',defaultvalue=\'1\',valueinfo =\'背景类型\',tips=\'默认是背景色\',bigclass =\'580\'',
  120 => 'pos =\'0\',no_order=\'33\',type=\'1\',style=\'3\',selectd=\'\',name =\'banner\',value=\'\',defaultvalue=\'\',valueinfo =\'banner设置\',tips=\'\',bigclass =\'0\'',
  121 => 'pos =\'1\',no_order=\'33\',type=\'9\',style=\'3\',selectd=\'\',name =\'about_titlecolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'标题颜色\',tips=\'默认是#000\',bigclass =\'580\'',
  122 => 'pos =\'0\',no_order=\'34\',type=\'4\',style=\'3\',selectd=\'$M$提示$T$1\',name =\'info\',value=\'1\',defaultvalue=\'1\',valueinfo =\'提示\',tips=\'此banner是图片不适合设置高度，如果觉得banner尺寸不合适请更换banner尺寸\',bigclass =\'477\'',
  123 => 'pos =\'1\',no_order=\'34\',type=\'9\',style=\'3\',selectd=\'\',name =\'about_desccolor\',value=\'#666\',defaultvalue=\'#666\',valueinfo =\'描述颜色\',tips=\'默认是#666\',bigclass =\'580\'',
  124 => 'pos =\'0\',no_order=\'35\',type=\'9\',style=\'3\',selectd=\'\',name =\'page_top_bgcolor\',value=\'#ccc\',defaultvalue=\'#ccc\',valueinfo =\'内页无banner背景色\',tips=\'\',bigclass =\'477\'',
  125 => 'pos =\'1\',no_order=\'35\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_news\',value=\'\',defaultvalue=\'\',valueinfo =\'首页新闻区块\',tips=\'\',bigclass =\'0\'',
  126 => 'pos =\'0\',no_order=\'36\',type=\'9\',style=\'3\',selectd=\'\',name =\'bannersub_color\',value=\'#fff\',defaultvalue=\'#fff\',valueinfo =\'内页无banner字体色\',tips=\'\',bigclass =\'477\'',
  127 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'483\'',
  128 => 'pos =\'0\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'btn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'电脑端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'477\'',
  129 => 'pos =\'1\',no_order=\'37\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_news_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'483\'',
  130 => 'pos =\'0\',no_order=\'38\',type=\'2\',style=\'3\',selectd=\'\',name =\'mbtn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'手机端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'477\'',
  131 => 'pos =\'1\',no_order=\'38\',type=\'9\',style=\'3\',selectd=\'\',name =\'news_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'区块背景颜色\',tips=\'默认为#f5f5f5\',bigclass =\'483\'',
  132 => 'pos =\'1\',no_order=\'39\',type=\'7\',style=\'3\',selectd=\'\',name =\'news_bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px高自定义的图片，上传区块背景图会覆盖区块背景色\',bigclass =\'483\'',
  133 => 'pos =\'0\',no_order=\'39\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_contact\',value=\'\',defaultvalue=\'\',valueinfo =\'底部联系信息设置\',tips=\'\',bigclass =\'0\'',
  134 => 'pos =\'1\',no_order=\'40\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目调用\',tips=\'调用子栏目列表以及子栏目下内容列表的标题、描述、时间\',bigclass =\'483\'',
  135 => 'pos =\'0\',no_order=\'40\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_tel\',value=\'\',defaultvalue=\'\',valueinfo =\'服务热线\',tips=\'\',bigclass =\'606\'',
  136 => 'pos =\'1\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'内容调用条数\',tips=\'默认为调用8条\',bigclass =\'483\'',
  137 => 'pos =\'0\',no_order=\'41\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_dsc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字\',tips=\'\',bigclass =\'606\'',
  138 => 'pos =\'1\',no_order=\'42\',type=\'9\',style=\'3\',selectd=\'\',name =\'tab_active_color\',value=\'#f01308\',defaultvalue=\'#f01308\',valueinfo =\'鼠标经过栏目颜色\',tips=\'默认为#f01308\',bigclass =\'483\'',
  139 => 'pos =\'0\',no_order=\'42\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_wx_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'微信\',tips=\'\',bigclass =\'606\'',
  140 => 'pos =\'0\',no_order=\'43\',type=\'7\',style=\'3\',selectd=\'\',name =\'footinfo_wx\',value=\'\',defaultvalue=\'\',valueinfo =\'微信二维码\',tips=\'\',bigclass =\'606\'',
  141 => 'pos =\'1\',no_order=\'43\',type=\'9\',style=\'3\',selectd=\'\',name =\'news_titlecolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'标题颜色\',tips=\'默认是#000\',bigclass =\'483\'',
  142 => 'pos =\'0\',no_order=\'44\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_qq_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ\',tips=\'\',bigclass =\'606\'',
  143 => 'pos =\'1\',no_order=\'44\',type=\'9\',style=\'3\',selectd=\'\',name =\'news_desccolor\',value=\'#666\',defaultvalue=\'#666\',valueinfo =\'描述颜色\',tips=\'默认是#666\',bigclass =\'483\'',
  144 => 'pos =\'0\',no_order=\'45\',type=\'4\',style=\'3\',selectd=\'$M$个人QQ$T$1$M$企业营销QQ$T$2\',name =\'foot_info_qqtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ类型\',tips=\'个人QQ和企业营销QQ超链接结构不一样，因此请务必选择正确。\',bigclass =\'606\'',
  145 => 'pos =\'1\',no_order=\'45\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_column_xs\',value=\'1\',defaultvalue=\'1\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\',bigclass =\'483\'',
  146 => 'pos =\'0\',no_order=\'46\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_qq\',value=\'\',defaultvalue=\'\',valueinfo =\'QQ号码\',tips=\'点击QQ链接可直接对话，需要先到 shang.qq.com 免费开通。<br/>企业营销QQ 无需开通\',bigclass =\'606\'',
  147 => 'pos =\'1\',no_order=\'46\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于或等于768像素且小于992像素\',bigclass =\'483\'',
  148 => 'pos =\'0\',no_order=\'47\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_sina_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'新浪微博\',tips=\'\',bigclass =\'606\'',
  149 => 'pos =\'1\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器窗口宽度大于或等于992像素且小于1600像素\',bigclass =\'483\'',
  150 => 'pos =\'0\',no_order=\'48\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_sina\',value=\'\',defaultvalue=\'\',valueinfo =\'新浪微博网址\',tips=\'请输入微博网址\',bigclass =\'606\'',
  151 => 'pos =\'1\',no_order=\'48\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器窗口宽度大于或等于1600像素\',bigclass =\'483\'',
  152 => 'pos =\'1\',no_order=\'49\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_case\',value=\'\',defaultvalue=\'\',valueinfo =\'首页服务案例区块\',tips=\'\',bigclass =\'0\'',
  153 => 'pos =\'0\',no_order=\'49\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_twitterok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'twitter（推特）\',tips=\'\',bigclass =\'606\'',
  154 => 'pos =\'1\',no_order=\'50\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'563\'',
  155 => 'pos =\'0\',no_order=\'50\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_twitter\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter网址\',tips=\'\',bigclass =\'606\'',
  156 => 'pos =\'1\',no_order=\'51\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'563\'',
  157 => 'pos =\'0\',no_order=\'51\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_googleok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'google+\',tips=\'\',bigclass =\'606\'',
  158 => 'pos =\'1\',no_order=\'52\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_case_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\',bigclass =\'563\'',
  159 => 'pos =\'0\',no_order=\'52\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_google\',value=\'\',defaultvalue=\'\',valueinfo =\'google+网址\',tips=\'\',bigclass =\'606\'',
  160 => 'pos =\'1\',no_order=\'53\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'默认调用8条\',bigclass =\'563\'',
  161 => 'pos =\'0\',no_order=\'53\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_facebookok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'Facebook\',tips=\'\',bigclass =\'606\'',
  162 => 'pos =\'1\',no_order=\'54\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于或等于768像素且小于992像素\',bigclass =\'563\'',
  163 => 'pos =\'0\',no_order=\'54\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_facebook\',value=\'\',defaultvalue=\'\',valueinfo =\'Facebook网址\',tips=\'\',bigclass =\'606\'',
  164 => 'pos =\'1\',no_order=\'55\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器窗口宽度大于或等于992像素且小于1600像素\',bigclass =\'563\'',
  165 => 'pos =\'0\',no_order=\'55\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_emailok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'邮箱\',tips=\'\',bigclass =\'606\'',
  166 => 'pos =\'1\',no_order=\'56\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器窗口宽度大于或等于1600像素\',bigclass =\'563\'',
  167 => 'pos =\'0\',no_order=\'56\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱地址\',tips=\'\',bigclass =\'606\'',
  168 => 'pos =\'0\',no_order=\'57\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_time\',value=\'周一至周五 9：00—18：00\',defaultvalue=\'周一至周五 9：00—18：00\',valueinfo =\'时间\',tips=\'\',bigclass =\'606\'',
  169 => 'pos =\'1\',no_order=\'57\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_case_column_xs\',value=\'2\',defaultvalue=\'2\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\',bigclass =\'563\'',
  170 => 'pos =\'1\',no_order=\'58\',type=\'9\',style=\'3\',selectd=\'\',name =\'index_case_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'区块背景色\',tips=\'默认#f5f5f5\',bigclass =\'563\'',
  171 => 'pos =\'1\',no_order=\'59\',type=\'7\',style=\'3\',selectd=\'\',name =\'index_case_bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px高自定义的图片，上传区块背景图会覆盖区块背景色\',bigclass =\'563\'',
  172 => 'pos =\'1\',no_order=\'60\',type=\'4\',style=\'3\',selectd=\'背景色$T$1$M$背景图$T$0\',name =\'casebg_type\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景类型\',tips=\'\',bigclass =\'563\'',
  173 => 'pos =\'1\',no_order=\'61\',type=\'2\',style=\'3\',selectd=\'\',name =\'caseimg_x\',value=\'480\',defaultvalue=\'480\',valueinfo =\'缩略图宽\',tips=\'默认是480px\',bigclass =\'563\'',
  174 => 'pos =\'1\',no_order=\'62\',type=\'2\',style=\'3\',selectd=\'\',name =\'caseimg_y\',value=\'350\',defaultvalue=\'350\',valueinfo =\'缩略图高\',tips=\'默认是350px\',bigclass =\'563\'',
  175 => 'pos =\'1\',no_order=\'63\',type=\'9\',style=\'3\',selectd=\'\',name =\'case_titlecolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'标题颜色\',tips=\'默认是#000\',bigclass =\'563\'',
  176 => 'pos =\'1\',no_order=\'64\',type=\'9\',style=\'3\',selectd=\'\',name =\'case_desccolor\',value=\'#666\',defaultvalue=\'#666\',valueinfo =\'描述颜色\',tips=\'默认是#666\',bigclass =\'563\'',
  177 => 'pos =\'1\',no_order=\'65\',type=\'9\',style=\'3\',selectd=\'\',name =\'caseimg_title\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'图片标题颜色\',tips=\'默认是#000\',bigclass =\'563\'',
  178 => 'pos =\'1\',no_order=\'66\',type=\'9\',style=\'3\',selectd=\'\',name =\'caseimg_desc\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'图片描述颜色\',tips=\'默认是#000\',bigclass =\'563\'',
  179 => 'pos =\'1\',no_order=\'67\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_service\',value=\'\',defaultvalue=\'\',valueinfo =\'首页服务区块\',tips=\'\',bigclass =\'0\'',
  180 => 'pos =\'1\',no_order=\'68\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_service_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'625\'',
  181 => 'pos =\'1\',no_order=\'69\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_service_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'\',bigclass =\'625\'',
  182 => 'pos =\'1\',no_order=\'70\',type=\'6\',style=\'3\',selectd=\'\',name =\'index_service_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'调用子栏目标题、描述、小图标\',bigclass =\'625\'',
  183 => 'pos =\'1\',no_order=\'71\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_service_column_xxl\',value=\'4\',defaultvalue=\'4\',valueinfo =\'大尺寸电脑显示列数\',tips=\'大尺寸电脑：浏览器窗口宽度大于或等于1600像素\',bigclass =\'625\'',
  184 => 'pos =\'1\',no_order=\'72\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_service_column_lg\',value=\'4\',defaultvalue=\'4\',valueinfo =\'普通电脑显示列数\',tips=\'普通电脑：浏览器窗口宽度大于或等于992像素且小于1600像素\',bigclass =\'625\'',
  185 => 'pos =\'1\',no_order=\'73\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_service_column_md\',value=\'2\',defaultvalue=\'2\',valueinfo =\'平板显示列数\',tips=\'平板：浏览器宽度大于或等于768像素且小于992像素\',bigclass =\'625\'',
  186 => 'pos =\'1\',no_order=\'74\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_service_column_xs\',value=\'1\',defaultvalue=\'1\',valueinfo =\'手机显示列数\',tips=\'手机：浏览器宽度小于768像素\',bigclass =\'625\'',
  187 => 'pos =\'1\',no_order=\'75\',type=\'9\',style=\'3\',selectd=\'\',name =\'service_bgcolor\',value=\'#f5f5f5\',defaultvalue=\'#f5f5f5\',valueinfo =\'区块背景色\',tips=\'默认是#f5f5f5\',bigclass =\'625\'',
  188 => 'pos =\'1\',no_order=\'76\',type=\'7\',style=\'3\',selectd=\'\',name =\'service_bgpic\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议上传宽为1920px高自定义的图片\',bigclass =\'625\'',
  189 => 'pos =\'1\',no_order=\'77\',type=\'4\',style=\'3\',selectd=\'背景色$T$1$M$背景图片$T$0\',name =\'sevicebg_type\',value=\'1\',defaultvalue=\'1\',valueinfo =\'背景类型\',tips=\'默认是背景色\',bigclass =\'625\'',
  190 => 'pos =\'1\',no_order=\'78\',type=\'9\',style=\'3\',selectd=\'\',name =\'service_titlecolor\',value=\'#000\',defaultvalue=\'#000\',valueinfo =\'标题颜色\',tips=\'默认是#000\',bigclass =\'625\'',
  191 => 'pos =\'1\',no_order=\'79\',type=\'9\',style=\'3\',selectd=\'\',name =\'service_desccolor\',value=\'#666\',defaultvalue=\'#666\',valueinfo =\'描述颜色\',tips=\'默认是#666\',bigclass =\'625\'',
  192 => 'pos =\'1\',no_order=\'80\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'serviceok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块显示开关\',tips=\'\',bigclass =\'625\'',
);
$no='metv7x';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>